#!/bin/bash

systemctl restart vpp

#sleep 10

#vppctl set interface ip address TenGigabitEthernet1/0/0 198.18.0.1/24
#vppctl set interface ip address TenGigabitEthernet1/0/1 198.19.0.1/24
#vppctl set interface state TenGigabitEthernet1/0/0 up
#vppctl set interface state TenGigabitEthernet1/0/1 up
#vppctl set ip neighbor TenGigabitEthernet1/0/0 198.18.0.2 b8:ca:3a:62:3c:40
#vppctl set ip neighbor TenGigabitEthernet1/0/1 198.19.0.2 b8:ca:3a:62:3c:42
sleep 80

vppctl nat44 plugin enable sessions $(($1*2))
echo "[VPP] $(($1*2)) connections registered"
sleep 5
vppctl set interface ip address TenGigabitEthernet1/0/0 198.18.0.1/24
vppctl set interface ip address TenGigabitEthernet1/0/1 198.19.0.1/24
vppctl set interface state TenGigabitEthernet1/0/0 up
vppctl set interface state TenGigabitEthernet1/0/1 up
vppctl set interface nat44 out TenGigabitEthernet1/0/1 output-feature
vppctl set ip neighbor TenGigabitEthernet1/0/0 198.18.0.2 b8:ca:3a:62:3c:40
vppctl set ip neighbor TenGigabitEthernet1/0/1 198.19.0.2 b8:ca:3a:62:3c:42
vppctl nat44 add interface address TenGigabitEthernet1/0/1
vppctl set nat timeout udp 20000
